name: testing

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.x

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build server
        run: make build

  linter:
    runs-on: ubuntu-latest
    name: Run linter
    needs:
      - build
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.x

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run linter
        run: make lint

  test:
    runs-on: ubuntu-latest
    name: Run tests
    needs:
      - linter
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.x

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run test
        run: |
          export APP_ENV=development
          export TELEGRAM_KEY=Example
          export MONGO_DB_NAME=Example
          export MONGO_DB_URL=http://127.0.0.1
          export ITERATION=15
          make test
